Completed react-accordion-component challenge.
alexei-dayrit/c0122-code-solutions pull request #127
Opened 2022-04-01 21:58 UTC by alexei-dayrit

https://user-images.githubusercontent.com/87846307/161346444-ca841dd3-fc6c-4813-b36b-4fe0c2c9b6a5.mov

2022-04-02 01:07 UTC, thebearingedge requested changes
Excellent, just a little reorganization.

2022-04-02 01:07 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +        text: `JavaScript, often abbreviated as JS, is
These should be passed into the accordion as a `topics` prop in index.jsx

2022-04-03 01:00 UTC, alexei-dayrit commented
https://user-images.githubusercontent.com/87846307/161406716-31a8058a-8fb8-4476-b986-7d8c149e8114.mov

2022-04-03 23:24 UTC, thebearingedge approved these changes

2022-04-04 02:49 UTC, merged