Array manipulation 2
alexei-dayrit/c0122-code-solutions pull request #61
Opened 2022-02-13 04:06 UTC by alexei-dayrit

<img width="883" alt="Screen Shot 2022-02-12 at 7 35 17 PM" src="https://user-images.githubusercontent.com/87846307/153738161-cd272364-3b1b-4307-b5ba-cdbf5059ebf3.png">

2022-02-14 02:30 UTC, thebearingedge requested changes

2022-02-14 02:30 UTC, thebearingedge commented on array-manipulation-2/src/drop.js
> +    }
You can start your `i` variable higher than `0` so you don't need an `if` statement.

2022-02-14 02:30 UTC, thebearingedge commented on array-manipulation-2/src/take-right.js
> +  }
You can start your loop later than `0`.

2022-02-14 02:30 UTC, thebearingedge commented on array-manipulation-2/src/take.js
> +    }
Your condition expression doesn't need to go all the way to `array.length`.

2022-02-19 20:16 UTC, alexei-dayrit commented
![Screen Shot 2022-02-19 at 12 16 34 PM](https://user-images.githubusercontent.com/87846307/154817611-3569ef1c-36c4-4d23-8e88-56962744b875.png)

2022-02-20 19:38 UTC, thebearingedge requested changes

2022-02-20 19:38 UTC, thebearingedge commented on array-manipulation-2/src/take-right.js
> +      return array;
It's best to get guards like this out of the way before your loop even starts, since you only need to check the condition on line 15 once.

2022-02-20 19:38 UTC, thebearingedge commented on array-manipulation-2/src/take.js
> +    }
Same here. No need to even start the loop if the array is empty. Alternatively, you could make your loop's condition expression more robust.

```js
for (var i = 0; i < count && i < array.length; i++) {
```

2022-02-20 20:15 UTC, thebearingedge approved these changes

2022-02-20 21:43 UTC, merged