Object manipulation 2
alexei-dayrit/c0122-code-solutions pull request #62
Opened 2022-02-19 21:34 UTC by alexei-dayrit

![Screen Shot 2022-02-19 at 1 32 28 PM](https://user-images.githubusercontent.com/87846307/154819833-e6f17255-e12f-439a-8466-310b7531d0e9.png)

2022-02-20 19:44 UTC, thebearingedge requested changes

2022-02-20 19:44 UTC, thebearingedge commented on object-manipulation-2/src/omit.js
> +    if (prop === keys[0] || prop === keys[1]) {
What will you do when there are more that two keys though? Try to rework your solution to handle more than just two keys.

2022-02-20 19:44 UTC, thebearingedge commented on object-manipulation-2/src/pick.js
> +      newObject[prop] = source[prop];
Same here. Try to think about the problem slightly differently. You might receive any number of keys.

2022-02-25 05:19 UTC, alexei-dayrit commented
Changed pick.js and omit.js:

![Screen Shot 2022-02-24 at 9 14 18 PM](https://user-images.githubusercontent.com/87846307/155658312-3b2c4d25-d019-4967-af59-009869b3ad57.png)

2022-02-26 21:42 UTC, merged